### PR TITLE
New pull request

### PR DESCRIPTION
**Pull request by MarxTown**
2nd pull request adhering to non-zip file

### CODE REVIEW

**Comment by CharlesAHunt** [comment]
Hey Chris! Thanks for the PR. We'll be having a look at your submitted code this week. You'll notice some comments on your PR from someone at Headstorm by the end of the week, you'll just need to respond to any comments and then the Challenge will be complete. +1

**Comment by MarxTown** [comment]
Ok sounds good!

**Comment by MarxTown** [comment]
No rush, but I do want to reaffirm I'm still interested in hearing feedback!

**Comment by tproffitt-headstorm** [comment]
Hi Chris!  Thanks for your submission.  Question for you re: front end challenge:  Say the user input is not a valid email address, i.e. foo.bar.com. How would you enforce and message to the user that there is an input error?

**Comment by MarxTown** [comment]
Hi there! Yeah I knew that only simply leaving the client-side "type" attribute as "email" in the HTML file wasn't really enough validation in that there is nothing server-side preventing someone from passing garbage that doesn't adhere to an actual email address. Someone could easily just post a non-valid email with something like Postman and it would go completely through so long as the same captcha token was passed with it. I really should have done some server-side regex code or something that maintained that the string was something like "string@string.string". And I guess if I really wanted to be thorough I could make sure the last part of the email was a proper domain suffix.

**Comment by MarxTown** [comment]
And as far as UI details go, I would have just probably done a simple JS alert message like how I did with the empty string error message, but I'm also usually one not to overly concern myself with UX related stuff unless it's pretty important. I'm sure there is a more "nice" way of presenting the error to the user or something like that.

**Comment by Sway71** [comment]
Totally the right idea on the server-side input validation :) In general, do you think the responses should look different based upon whether the email is invalid vs the email already exists?

Also, sorry to hit you on the front end side again, but I had a follow-up to Tim's question: If you have multiple inputs, and only some of them are invalid, how would you signify that only those inputs need fixing and automatically scroll the page to the first invalid input?

**Comment by MarxTown** [comment]
Of course the responses should be different! An invalid email address is completely a syntax issue; whereas, a duplicate email is more related to semantics in that the rules of email addresses, being that everyone has a unique address, no two people should be able to register the same email associated with themself. It would be very cryptic if a user received an "invalid email" message when the reality is that it's perfectly valid in that it adheres to the typical rules of the language (email language? haha).

Once again the server should be made aware of the fact that the user did not send all the proper parameters required and should return a list of booleans to the client which indicate which required fields have been set and which haven't. With this list, the client could then update some CSS values to make the related fields appear with a red outline. In order to scroll to the appropriate field (first one), the fields would need to be numbered by something like giving the ID a number from top to bottom. Then you could call something like the jQuery animate() function to which ever ID is the lowest value. More or less the logic would have to be something like that. Furthermore, the server doesn't have to be "aware" of any of this scrolling animation that takes place in that it isn't concerning validation of information or anything like that. Just should be client-side animation done with HTML/CSS/jQuery.

**Comment by CharlesAHunt** [comment]
Thanks for all your answers @MarxTown  ! This wraps up the Github challenge portion. Could you respond to this comment with your email address so someone at Headstorm can contact you regarding next steps?  Thanks!  :+1:

**Comment by MarxTown** [comment]
Thanks for the feedback and questions! My email address is chrisrmarx@gmail.com

Hope to hear from you guys soon!

**Pull request closed without merging**
